# Generated by Django 3.0.2 on 2020-04-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200402_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Customer'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cut',
            field=models.CharField(blank=True, choices=[('Quarter Sock', 'Quarter Sock'), ('Crew Sock', 'Crew Sock'), ('Knee High Sock', 'Knee High Sock')], max_length=250, null=True, verbose_name='Cuts'),
        ),
    ]
