# Generated by Django 3.0.2 on 2020-02-11 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=250)),
                ('street2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zip', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youth', models.IntegerField(blank=True, null=True)),
                ('small', models.IntegerField(blank=True, null=True)),
                ('medium', models.IntegerField(blank=True, null=True)),
                ('large', models.IntegerField(blank=True, null=True)),
                ('extra_large', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(blank=True, choices=[('VAPOR', 'Vapor'), ('TWO_TONE', 'Two Tone'), ('SPLIT_TOP', 'Split Top'), ('STRIPE', 'Stripe'), ('DOUBLE_STRIPE', 'Double Stripe'), ('TRIPLE_STRIPE', 'Triple Stripe')], max_length=250, null=True, verbose_name='Designs')),
                ('primary_color', models.CharField(max_length=250)),
                ('secondary_color', models.CharField(blank=True, max_length=250, null=True)),
                ('toe_primary_text', models.CharField(blank=True, max_length=250, null=True)),
                ('toe_secondary_text', models.CharField(blank=True, max_length=250, null=True)),
                ('brim_primary_text', models.CharField(blank=True, max_length=250, null=True)),
                ('brim_secondary_text', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(upload_to='logos/%Y/%m/%d')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Customer')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Sizes')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Address'),
        ),
    ]
