# Generated by Django 3.0.2 on 2020-02-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200211_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Sizes'),
        ),
    ]
