# Generated by Django 3.0.2 on 2020-03-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200331_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
    ]
