# Generated by Django 3.0.2 on 2020-04-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200402_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='primary_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
